### ISSUE TITLE
数据库的表结构可以提供下吗？

### ISSUE THREAD

**Issue by echohlne** [2020-07-01/cloudnote#9]

**Comment by 2020-07-01** [comment]
<img width="367" alt="schedule" src="https://user-images.githubusercontent.com/42581836/87846886-050dd200-c906-11ea-8f1f-6bd7df9b366d.png">
<img width="370" alt="account" src="https://user-images.githubusercontent.com/42581836/87846888-07702c00-c906-11ea-9810-ddf861258d7c.png">
<img width="340" alt="file" src="https://user-images.githubusercontent.com/42581836/87846889-0939ef80-c906-11ea-862c-6c4a7264a127.png">
<img width="372" alt="note" src="https://user-images.githubusercontent.com/42581836/87846891-09d28600-c906-11ea-9452-3d0bb2f5ef7b.png">
<img width="373" alt="image" src="https://user-images.githubusercontent.com/42581836/87846890-09d28600-c906-11ea-921c-b77f9ea32baa.png">

**Comment by echohlne** [comment]
谢谢了~
